#!/usr/bin/env bash

set -euo pipefail

[ -e /opt/resource/common ] && cd /opt/resource/
. ./common

extract=true
if [ -z "$FILES" ]; then
    extract=false
fi
script="$(EXTRACT="$extract" envsubst "$(< scripts/put_files.vars)" < scripts/put_files.sh)"
echo "tar x script:" >&2
echo "$script" >&2
(
    cd "$1"
    ( IFS=$'\n' tar c $FILES ) | ssh -F "$CONFIG_PATH" "$HOSTNAME" "sh -c '$script'"
)
computed_version="$(compute_version "$(fetch_file_meta)")"
jq -r tostring << EOF
    {
        "version": $computed_version
    }
EOF
cleanup

exit 0
